refactor: replace next auth with lucia
arrocke/gloss-translation pull request #111
Opened 2023-06-20 13:21 UTC by arrocke

## What has changed

* removed nextauth in favor of lucia
* added routes for login, logout, and getting the session
* added a view for login
* added emails for invite and login

## Connected Issues

closes #108 

## QA Steps

### Login/Logout
1. Enter email on login view
2. Click link in sent email
3. Check that user is logged in
4. Click log out
5. Check that user is logged out

### Invite
1. Make sure you are logged in
2. Enter user info in the invite page
3. Click link in invite email
4. Check that new user is logged in.

## Post-Deployment

Will need to migrate existing users to new model

2023-06-23 09:50 UTC, Pertempto reviewed
I've started review on this. We're going on a camping trip this weekend, but hopefully I can continue on Monday.

2023-06-23 09:50 UTC, Pertempto commented on packages/api/shared/auth.ts
> +  // TODO: extract to env vars
Does this need done in this PR?

2023-06-23 09:50 UTC, Pertempto commented on packages/api/pages/api/auth/login.ts
> +        const url = new URL('http://localhost:4300/api/auth/login');
This won't work on production?

2023-06-24 03:31 UTC, arrocke commented
I addressed the environment variable issues, and found a way to get this working in preview URLs as well.

2023-06-26 09:55 UTC, Pertempto commented
I logged in with the default account, then attempted to add an account. I got this error in the API log:
```
PrismaClientValidationError: 
Invalid `prisma.authKey.create()` invocation:
{
  data: {
    id: 'email-verification:133cad8ef033fd1801a9fcdd',
    user_id: undefined,
?   hashed_password?: String | null,
    primary_key: false,
    expires: 1687776739404,
+   auth_user: {
+     create?: AuthUserCreateWithoutAuth_keyInput | AuthUserUncheckedCreateWithoutAuth_keyInput,
+     connectOrCreate?: AuthUserCreateOrConnectWithoutAuth_keyInput,
+     connect?: AuthUserWhereUniqueInput
+   }
  }
}
Argument auth_user for data.auth_user is missing.
Note: Lines with + are required, lines with ? are optional.
    at ti.validate (webpack-internal:///(api)/./prisma/client/runtime/library.js:8634:37)     
    at Wr.createMessage (webpack-internal:///(api)/./prisma/client/runtime/library.js:10057:20)
    at eval (webpack-internal:///(api)/./prisma/client/runtime/library.js:11327:49)
    at runInChildSpan (webpack-internal:///(api)/./prisma/client/runtime/library.js:7117:59)  
    at t11._executeRequest (webpack-internal:///(api)/./prisma/client/runtime/library.js:11327:33) {
  clientVersion: '4.11.0'
}
```

The strange thing is, a new row was successfully added to the `User` table.

2023-06-26 21:42 UTC, Pertempto commented
> I logged in with the default account, then attempted to add an account. I got this error in the API log:
>  ...

I added some `console.log` in `login.ts`

```
      if (key) {
        const token = randomBytes(12).toString('hex');
        console.log('Create key!');
        console.log(key);
        console.log(token);
        await auth.createKey(key.userId, {
          type: 'single_use',
          providerId: 'email-verification',
          providerUserId: token,
          password: null,
          expiresIn: 60 * 60,
        });
        console.log('success');
```

Here is the output
```
Create key!
{
  type: 'persistent',
  primary: true,
  providerId: 'username',
  providerUserId: 'devyn61@ethereal.email',
  userId: '0188d4d9-999d-26f9-a9df-e9df68c789b2',
  passwordDefined: false
}
0c979b5289806b17e607dc4b
success
PrismaClientValidationError: 
Invalid `prisma.authKey.create()` invocation:
{
  data: {
    id: 'email-verification:923d8b2e96b2e66e005ac06e',
    user_id: undefined,
?   hashed_password?: String | null,
    primary_key: false,
    expires: 1687819087652,
+   auth_user: {
+     create?: AuthUserCreateWithoutAuth_keyInput | AuthUserUncheckedCreateWithoutAuth_keyInput,
+     connectOrCreate?: AuthUserCreateOrConnectWithoutAuth_keyInput,
+     connect?: AuthUserWhereUniqueInput
+   }
  }
}
Argument auth_user for data.auth_user is missing.
Note: Lines with + are required, lines with ? are optional.
    at ti.validate (webpack-internal:///(api)/./prisma/client/runtime/library.js:8634:37)
    at Wr.createMessage (webpack-internal:///(api)/./prisma/client/runtime/library.js:10057:20)
    at eval (webpack-internal:///(api)/./prisma/client/runtime/library.js:11327:49)
    at runInChildSpan (webpack-internal:///(api)/./prisma/client/runtime/library.js:7117:59)
    at t11._executeRequest (webpack-internal:///(api)/./prisma/client/runtime/library.js:11327:33) {
  clientVersion: '4.11.0'
}
```

I don't understand the lucia key code very well, but it seems strange that the `providerUserId` is `devyn61@ethereal.email`. Should it be the email I am providing? In this case, `test@example.com`

2023-06-26 21:46 UTC, Pertempto commented
Something is failing with the `auth.createKey` in `api/users/index.ts`, but I don't know enough about lucia to debug.

2023-06-26 21:48 UTC, Pertempto requested changes
See my above comments about user invite bug.

2023-06-28 03:08 UTC, arrocke commented
Should be good now

2023-06-28 09:29 UTC, Pertempto approved these changes
Works great!

2023-06-28 21:17 UTC, merged