feat: modify and remove language members
arrocke/gloss-translation pull request #132
Opened 2023-07-28 23:39 UTC by arrocke

## What has changed

## Connected Issues

## QA Steps

## Post-Deployment

- [ ] Nothing required

2023-08-03 22:36 UTC, Pertempto requested changes
Roles don't seem to be applied correctly. I create a user with Translator role, and they get stuck on the loading indicator when they try to access the translate page. I add the Admin role, and they get the same result, with no option to manage the language either.

2023-08-03 22:36 UTC, Pertempto commented on packages/web/src/shared/components/actions/Button.tsx
>  export const buttonTailwindClasses =
I think we want to remove this, now that it is no longer referenced anywhere.

2023-08-03 23:45 UTC, arrocke commented
@Pertempto I hadn't merged main which had the changes from the other PR which cleaned up the access control. Can you try again?

2023-08-04 01:11 UTC, Pertempto commented
If an admin changes their own access, the UI can get a little funky because it still uses the old access rights. The API protects everything though, and the frontend updates after a page refresh.

2023-08-04 01:12 UTC, Pertempto commented
Everything seems to work well!

2023-08-04 01:13 UTC, Pertempto approved these changes

2023-08-04 01:27 UTC, merged