refactor: extract db to separate package
arrocke/gloss-translation pull request #148
Opened 2023-08-18 22:28 UTC by arrocke

## What has changed

* New `@translation/db` package that exports prisma types and a prisma client
* I changed the location of the client to use the default which generates the client as a node module (`@prisma/client`). The other PR/branch generates the client in the package, which would allow us to support multiple prisma clients, but that is blocked by https://github.com/prisma/prisma/issues/19784

## Connected Issues

## QA Steps

## Post-Deployment

- [x] Nothing required

2023-08-18 22:31 UTC, arrocke commented on packages/db/src/index.ts
> +export * from '@prisma/client';
For now, this package just exports the prisma client. Doing it this way will allow us to eventually bundle the client in this package so we could support multiple prisma schemas.

2023-08-18 22:31 UTC, arrocke commented on packages/api/shared/db.ts
>  export const client = new PrismaClient();
Now when we need to connect to the database, we import from `@translation/db` rather than `@prisma/client`. Same thing for prisma types.

2023-08-21 09:15 UTC, Pertempto requested changes
Hmmm, I'm not sure what's going on

`npm i` runs fine.

Then I try `nx serve api` and `nx serve web`. I tried to access `http://localhost:4200/languages/en/verses/01001001`, but all the API requests hang indefinitely. 

Did I miss a setup step?

2023-08-21 09:15 UTC, Pertempto commented on docs/db.md
> +1. Set the `DATABASE_URL` env var in `packages/api/.env.local` and `packages/db/.env.local` to the postgres connection string. You may need to include a username and password in the connection string
Do we still need it in `packages/api/.env.local`?

2023-08-21 09:15 UTC, Pertempto commented on .eslintignore
> +packages/db/src/client
This directory doesn't exist.

2023-08-21 23:31 UTC, arrocke commented on docs/db.md
> +1. Set the `DATABASE_URL` env var in `packages/api/.env.local` and `packages/db/.env.local` to the postgres connection string. You may need to include a username and password in the connection string
Yep, the one in the db package doesn't get loaded when the api project is served

2023-08-21 23:32 UTC, arrocke commented
Did you see any error messages in the api logs?

2023-08-22 09:08 UTC, Pertempto commented
> Did you see any error messages in the api logs?

I manually went to the login page, waited a while for everything to load after I submitted username and password, and it finally loaded.

It did get this error in the API logs:
```
Invalid `prisma.authSession.delete()` invocation:
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
    at Zr.handleRequestError (C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\node_modules\@prisma\client\runtime\library.js:171:6414)
    at Zr.handleAndLogRequestError (C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\node_modules\@prisma\client\runtime\library.js:171:5948)
    at Zr.request (C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\node_modules\@prisma\client\runtime\library.js:171:5786)
    at async t._request (C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\node_modules\@prisma\client\runtime\library.js:174:10455)
    at async Object.deleteSession (file:///C:/Users/addis/SoftwareProjects/gloss-translation/gloss-translation/node_modules/@lucia-auth/adapter-prisma/index.js:100:13) {
  digest: undefined
}
```

2023-08-22 09:12 UTC, Pertempto commented
Otherwise, everything seems to load. It almost seems like it takes longer to load glosses. It is taking 3+ seconds to load glosses for each verse

<img width="408" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/f87b6cc7-8868-45fe-a457-8cdae864ac4d">


Hopefully this doesn't occur on our production server, or the UX quality will really drop.

2023-08-22 09:15 UTC, Pertempto approved these changes

2023-08-22 09:25 UTC, Pertempto commented
I think we should go ahead and merge this, so I can keep going on #134.

If slow load times is a problem on production, we can create a separate issue for it.

2023-08-22 17:54 UTC, merged