feat: use Noto Sans as interface font
arrocke/gloss-translation pull request #244
Opened 2023-10-28 11:32 UTC by Pertempto

## What has changed

Use Noto Sans as our default interface font

## Connected Issues

Closes #239

## QA Steps

Use dev tools to inspect various parts of the interface and check that the font in the computed pane is Noto Sans

## Post-Deployment

- [ ] Nothing required

2023-10-28 11:34 UTC, Pertempto commented
This ONLY sets the default interface font. If we want to set different fonts based on currently selected interface language, I'd be open to hearing possible strategies.

2023-10-28 22:54 UTC, arrocke requested changes
Let's tackle picking the right noto font separately

2023-10-28 22:54 UTC, arrocke commented on packages/web/tailwind.config.js
> +      sans: '"Noto Sans"',
We should add a fallback fonts for while our font is still loading. Here is how tailwind recommends doing that: https://tailwindcss.com/docs/font-family#customizing-the-default-font

2023-10-30 15:22 UTC, arrocke approved these changes

2023-10-30 21:19 UTC, merged