refactor: upgrade lucia and prisma
arrocke/gloss-translation pull request #372
Opened 2024-03-05 18:06 UTC by arrocke

## What has changed

## Connected Issues

## QA Steps

## Post-Deployment

- [ ] Nothing required

2024-03-06 09:38 UTC, Pertempto commented on packages/api/pages/api/email/verify.ts
> +          subject: 'Password Changed',
Is this accurate?

2024-03-06 09:43 UTC, Pertempto commented
Unrelate to this PR, but I saw this when signing in from an invite.

![image](https://github.com/globalbibletools/gbt/assets/17209828/c3669392-52a2-4ad7-a505-c65b942deb1d)

2024-03-06 09:46 UTC, Pertempto commented
I updated a user's email, clicked the verification link, then logged back in.

I then attempted to update the user's password

![image](https://github.com/globalbibletools/gbt/assets/17209828/51b23f6c-c69b-4e17-8fa5-2de347d560ed)

```
MissingEmailAddressError: We can't send emails to user with id 018e1324-0c33-e9a5-8642-6a835699f649 because they are missing an email address.
    at Object.sendEmail (webpack-internal:///(api)/./shared/mailer.ts:55:23)
    at Object.handler (webpack-internal:///(api)/./pages/api/users/[userId].ts:88:74)
    at async eval (webpack-internal:///(api)/./shared/Route.ts:171:21)
    at async eval (webpack-internal:///(api)/./shared/Route.ts:230:21)
```

2024-03-06 09:48 UTC, Pertempto commented
The bug occurs when I try to update the password for any user.

2024-03-06 09:52 UTC, Pertempto requested changes
Everything worked really well except for updating a user's password.

Should the seed file be updated?

2024-03-07 22:09 UTC, arrocke commented
I updated the seed file and fixed the mailer

2024-03-08 10:01 UTC, Pertempto commented on packages/api/pages/api/email/verify.ts
> +          subject: 'Password Changed',
@arrocke Shouldn't this subject be `"Email changed"`?

2024-03-08 10:17 UTC, Pertempto approved these changes
Password update works now :+1:

Please see https://github.com/globalbibletools/gbt/pull/372#discussion_r1517506577, otherwise this looks good!

2024-03-12 00:45 UTC, merged